[package]
name = "corsairmi"
version = "0.3.2"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
repository = "https://github.com/newAM/corsairmi-rs"
license = "MIT"
description = "Read data from Corsair RMi and HXi series power supplies."
readme = "README.md"
keywords = ["corsair", "power-supply"]
categories = ["hardware-support"]
homepage = "https://github.com/newAM/corsairmi-rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
libc = "0.2"

[dependencies.tokio]
version = "1"
features = ["fs"]
optional = true

[dev-dependencies.tokio]
version = "1"
features = ["full"]

[package.metadata.docs.rs]
all-features = true
